image: gitlab/dind

services:
  - gitlab/dind

before_script:
  - docker info
  - apt-get update && apt-get install -y --no-install-recommends make linux-image-generic

job:
  script:
    - make sd-image
