image: gitlab/dind

services:
  - gitlab/dind

before_script:
  - docker info
  - apt-get update && apt-get install -y make linux-image-amd64

variables:
  LIBGUESTFS_DEBUG: 1 
  LIBGUESTFS_TRACE: 1

job:
  script:
    - make sd-image
