image: gitlab/dind

services:
  - gitlab/dind

before_script:
  - apt-get update
  - apt-get install -y make

variables:
  LIBGUESTFS_DEBUG: 1 
  LIBGUESTFS_TRACE: 1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

job:
  script:
    - make sd-image
